package com.example.pepenet.vpn

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.provider.Settings
import android.security.KeyChain
import java.io.File
import java.security.KeyStore
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate
import java.util.Base64

/**
 * The local root CA the DANE proxy signs .pepe leaves with. It is generated by
 * the native node on first connect (pepenet-root-pepe.crt) and carries a
 * critical Name Constraint: it can ONLY vouch for *.pepe — never for real
 * websites.
 *
 * Android does not let apps add trusted CAs silently. On Android 11+ the user
 * installs it once: Settings → Security → Encryption & credentials →
 * Install a certificate → CA certificate → pick "PepeNet-pepe-root.crt"
 * from Downloads. Chrome then shows a padlock on https://<name>.pepe.
 */
object CertificateManager {

    private const val CA_FILE = "pepenet-root-pepe.crt"
    const val EXPORT_NAME = "PepeNet-pepe-root.crt"

    fun caFile(context: Context): File = File(MeshSyncEngine.dataDir(context), CA_FILE)

    fun caExists(context: Context): Boolean = caFile(context).isFile

    private fun loadCa(context: Context): X509Certificate? {
        val f = caFile(context)
        if (!f.isFile) return null
        return try {
            f.inputStream().use {
                CertificateFactory.getInstance("X.509").generateCertificate(it) as X509Certificate
            }
        } catch (e: Exception) {
            null
        }
    }

    enum class TrustState { NO_CA, NOT_INSTALLED, OUTDATED, INSTALLED }

    /**
     * Where the user's CA store stands relative to the root on disk:
     * INSTALLED (exact match), OUTDATED (an older PepeNet root is installed —
     * e.g. after reinstalling the app), or NOT_INSTALLED.
     */
    fun trustState(context: Context): TrustState {
        val ours = loadCa(context) ?: return TrustState.NO_CA
        return try {
            val ks = KeyStore.getInstance("AndroidCAStore").apply { load(null) }
            var stale = false
            for (alias in ks.aliases().toList()) {
                if (!alias.startsWith("user:")) continue
                val c = ks.getCertificate(alias) as? X509Certificate ?: continue
                if (c.encoded.contentEquals(ours.encoded)) return TrustState.INSTALLED
                if (c.subjectX500Principal == ours.subjectX500Principal) stale = true
            }
            if (stale) TrustState.OUTDATED else TrustState.NOT_INSTALLED
        } catch (e: Exception) {
            TrustState.NOT_INSTALLED
        }
    }

    fun isInstalled(context: Context): Boolean = trustState(context) == TrustState.INSTALLED

    /** Copies the CA into Downloads. Returns the display path, or null. */
    fun exportToDownloads(context: Context): String? {
        val ca = loadCa(context) ?: return null
        val pem = buildString {
            append("-----BEGIN CERTIFICATE-----\n")
            Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(ca.encoded)
                .let { append(it) }
            append("\n-----END CERTIFICATE-----\n")
        }
        val resolver = context.contentResolver
        // replace an earlier export instead of piling up "(1)" copies
        resolver.delete(
            MediaStore.Downloads.EXTERNAL_CONTENT_URI,
            "${MediaStore.MediaColumns.DISPLAY_NAME}=?",
            arrayOf(EXPORT_NAME),
        )
        val values = ContentValues().apply {
            put(MediaStore.MediaColumns.DISPLAY_NAME, EXPORT_NAME)
            put(MediaStore.MediaColumns.MIME_TYPE, "application/x-x509-ca-cert")
            put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
        }
        val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values) ?: return null
        resolver.openOutputStream(uri)?.use { it.write(pem.toByteArray()) } ?: return null
        return "Downloads/$EXPORT_NAME"
    }

    val isSamsung: Boolean get() = Build.MANUFACTURER.equals("samsung", ignoreCase = true)

    /**
     * Candidate intents, most specific first: Android 10 and older install
     * directly; on 11+ we jump as deep into Settings as the device allows
     * (the credentials screen that holds "Install a certificate").
     */
    fun installIntents(context: Context): List<Intent> {
        val out = mutableListOf<Intent>()
        val ca = loadCa(context)
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R && ca != null) {
            out += KeyChain.createInstallIntent().apply {
                putExtra(KeyChain.EXTRA_CERTIFICATE, ca.encoded)
                putExtra(KeyChain.EXTRA_NAME, "PepeNet .pepe root")
            }
        }
        // AOSP / Pixel: Security › Encryption & credentials
        out += Intent().setClassName(
            "com.android.settings",
            "com.android.settings.Settings\$EncryptionAndCredentialsSettingsActivity",
        )
        // Samsung One UI: More security settings (holds "Install from device storage")
        if (isSamsung) {
            out += Intent().setClassName(
                "com.android.settings",
                "com.android.settings.Settings\$SecuritySettingsActivity",
            )
        }
        out += Intent(Settings.ACTION_SECURITY_SETTINGS)
        out += Intent(Settings.ACTION_SETTINGS)
        return out.map { it.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK) }
    }

    /** Human steps for this phone, shown next to the button. */
    fun steps(): List<String> = if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) listOf(
        "Tap Install certificate",
        "Name it PepeNet and confirm (set a screen lock if asked)",
        "Come back here — PepeNet detects it automatically",
    ) else if (isSamsung) listOf(
        "Tap Install certificate — it is saved to Downloads and Settings opens",
        "Security and privacy › More security settings › Install from device storage",
        "CA certificate › Install anyway › pick PepeNet-pepe-root.crt",
        "Come back here — PepeNet detects it, then restart Chrome",
    ) else listOf(
        "Tap Install certificate — it is saved to Downloads and Settings opens",
        "Encryption & credentials › Install a certificate › CA certificate",
        "Install anyway › pick PepeNet-pepe-root.crt",
        "Come back here — PepeNet detects it, then restart Chrome",
    )
}
